#server:
#  port: 8081
#
#spring:
#  application:
#    name: benefit-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#  config:
#    import: "optional:configserver:"