server:
  port: 8085

spring:
  application:
    name: notification-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
  
  redis:
    host: localhost
    port: 6379

notification:
  kafka:
    topic: notification-events

logging:
  level:
    com.goodjob.notification: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.kafka: INFO
    org.springframework.web.socket: INFO 