global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'benefit-service'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'candidate-service'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'company-service'
    static_configs:
      - targets: ['localhost:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'industry-service'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'job-service'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'mail-service'
    static_configs:
      - targets: ['localhost:8086']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['localhost:8087']
    metrics_path: '/actuator/prometheus'

  - job_name: 'posting-service'
    static_configs:
      - targets: ['localhost:8088']
    metrics_path: '/actuator/prometheus'

  - job_name: 'skill-service'
    static_configs:
      - targets: ['localhost:8089']
    metrics_path: '/actuator/prometheus'

  - job_name: 'speciality-service'
    static_configs:
      - targets: ['localhost:8090']
    metrics_path: '/actuator/prometheus'