server:
  port: 8083

spring:
  application:
    name: speciality-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: "optional:configserver:"

logging:
  config: ${spring.cloud.config.uri}/speciality-service/logging/logback-spring.xml