spring:
  application:
    name: posting-service
  config:
    import: 'configserver:http://localhost:8888'

# Fallback properties in case config server is not available
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always