server:
  port: 8082

spring:
  application:
    name: skill-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: "optional:configserver:"

logging:
  config: ${spring.cloud.config.uri}/skill-service/logging/logback-spring.xml