scrape_configs:
#  - job_name: 'micro-services'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ 'api-gateway:8080', 'host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083', 'host.docker.internal:8888', 'host.docker.internal:8761', 'host.docker.internal:8084', 'host.docker.internal:8085', 'host.docker.internal:8086', 'host.docker.internal:8087', 'host.docker.internal:8088', 'host.docker.internal:8089', 'host.docker.internal:8090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'api-gateway:8080' ]

  - job_name: 'metadata-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'metadata-service:8081' ]

  - job_name: 'candidate-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'candidate-service:8082' ]

  - job_name: 'company-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'company-service:8083' ]

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'config-server:8888' ]

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'eureka-server:8761' ]

  - job_name: 'job-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'job-service:8085' ]

  - job_name: 'mail-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'mail-service:8086' ]

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'notification-service:8087' ]

  - job_name: 'posting-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'posting-service:8088' ]