global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Các endpoints Actuator của Spring Boot applications
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'config-server:8888'
          - 'eureka-server:8761'
          - 'candidate-service:8080'
          - 'company-service:8080'
          - 'job-service:8080'
          - 'posting-service:8080'
          - 'skill-service:8080'
          - 'industry-service:8080'
          - 'speciality-service:8080'
          - 'benefit-service:8080'
          - 'mail-service:8080'
          - 'notification-service:8080'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: instance
        replacement: $1

  # Scraping metrics from Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape JVM metrics from Spring Boot applications
  - job_name: 'jvm-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'config-server:8888'
          - 'eureka-server:8761'
          - 'candidate-service:8080'
          - 'company-service:8080'
          - 'job-service:8080'
          - 'posting-service:8080'
          - 'skill-service:8080'
          - 'industry-service:8080'
          - 'speciality-service:8080'
          - 'benefit-service:8080'
          - 'mail-service:8080'
          - 'notification-service:8080'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: instance
        replacement: $1
      # Thêm label để phân biệt metrics loại jvm
      - target_label: 'metric_type'
        replacement: 'jvm'

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka1:9092'
          - 'kafka2:9092'
          - 'kafka3:9092'
    
  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432'] 