global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'benefit-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'candidate-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'company-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'industry-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'job-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'mail-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/actuator/prometheus'

  - job_name: 'posting-service'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/actuator/prometheus'

  - job_name: 'skill-service'
    static_configs:
      - targets: ['host.docker.internal:8089']
    metrics_path: '/actuator/prometheus'

  - job_name: 'speciality-service'
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: '/actuator/prometheus'