server:
  port: 8083

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/company_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 36000  # Thời gian mặc định (giây)
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.security: DEBUG
    com.goodjob.company: DEBUG