spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/posting
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    security:
      protocol: plaintext
    consumer:
      group-id: default-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
